name: cts_keygen
description: Generador de keys CTS para uso local en Flutter.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
